Chapter seven tasks
kadly/thinknetica_javascript pull request #7
Opened 2020-06-26 18:29 UTC by kadly

2020-06-27 09:00 UTC, arswarog requested changes

2020-06-27 09:00 UTC, arswarog commented on Продвинутая работа с функциями/ships/ships.js
> +                console.log('Error');
Стоит выкидывать ошибку. Например так:
`throw new Error(`Invalid direction "${direction}"`)`
Иначе если вызвать метод с не верным направлением то корабль не сдвинется но пройденная им дистанция всеравно будет увеличена

2020-06-27 09:00 UTC, arswarog commented on Продвинутая работа с функциями/ships/wharf.js
> +    this.mooredShips.pop(ship);
pop удаляет **последний** элемент из массива. Параметры он не принимает (а переданные игнорирует)
Эту строку надо будет исправить, например с помощью splice или filter

2020-06-27 09:00 UTC, arswarog commented on Продвинутая работа с функциями/ships/wharf.js
> +  this.moor = function (ship) {
Нет проверки на совпадение координат корабля и верфи
Если корабль находится не у верфи, как он может быть пришвартован к верфи?

2020-06-27 09:00 UTC, arswarog commented on Продвинутая работа с функциями/university/group.js
> +    return this.students.filter(student => !student.studentPresence() == false);
Используй что-нибудь одно
или 
student => !student.studentPresence()
или
student => student.studentPresence() === false

2020-06-29 05:03 UTC, kadly commented on Продвинутая работа с функциями/ships/wharf.js
> +  this.moor = function (ship) {
исправил

2020-06-29 05:08 UTC, kadly commented on Продвинутая работа с функциями/ships/wharf.js
> +  this.moor = function (ship) {
ещё исправил /university/group.js и твой соответствующий комментарий пропал почему-то.
Там раньше было
    return this.students.filter(student => !student.studentPresence() == false);
потому что не доглядел, а перенос строк не был настроен в редакторе.

2020-06-30 07:29 UTC, arswarog requested changes

2020-06-30 07:29 UTC, arswarog commented on Продвинутая работа с функциями/ships/wharf.js
> +    let indexOfThisShip = this.mooredShips.indexOf(thisShip);
Может тогда уже
this.mooredShips.indexOf(thisShip**[0]**);
ведь filter возвращает массив

Но правильнее и удобнее использовать findIndex
Почитай про методы find, findIndex 
https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/find
https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/findIndex

2020-06-30 07:29 UTC, arswarog commented on Продвинутая работа с функциями/ships/wharf.js
> +    let removedShip = this.mooredShips.splice(indexOfThisShip,1);
Отлично!

2020-07-02 10:48 UTC, arswarog requested changes

2020-07-02 10:48 UTC, arswarog commented on Продвинутая работа с функциями/ships/wharf.js
> +    )
Извиняюсь. я немного запутался в предыдущей версии кода где было
```js
let thisShip = this.mooredShips.filter(item => item == ship);
let indexOfThisShip = this.mooredShips.indexOf(thisShip);
let removedShip = this.mooredShips.splice(indexOfThisShip,1);
```
Исправляюсь:

Эта строчка не нужна ( в чем ее смысл?)
`let thisShip = this.mooredShips.filter(item => item == ship);`

Что именно ищет эта строчка?
let indexOfThisShip = this.mooredShips.indexOf(thisShip);
Ведь thisShip это массив и учитывая что это всегда новый массив то
indexOfThisShip **всегда** будет -1
Выходит что этот код работал неверно

**Итого:**
Когда требуется найти конкретный объект
const shipIndex = this.mooredShips.indexOf(**ship**) 
или
когда ищешь по какому-либо условию
const shipIndex = this.mooredShips.findIndex(item => item === ship)

В данном случае indexOf наиболее подходящий вариант

2020-07-03 11:36 UTC, arswarog approved these changes

2020-07-03 12:22 UTC, merged